diwako/armor_plates_system

- addons/main/functions/fnc_receiveDamage.sqf
- addons/main/initSettings.sqf
- addons/main/stringtable.xml
Will only work with `HandleDamageEh`.
> Add protect only torso setting

- addons/main/XEH_postInit.sqf
- addons/main/script_component.hpp
> fix initial left click issue with ace dragging

- addons/main/XEH_postInit.sqf
- addons/main/functions/fnc_handleHealEh.sqf
- addons/main/functions/fnc_setUnconscious.sqf
Sets the animation when waking up, also makes all machines check if the unit is stuck in an unconscious animation on their end
> fix for ace dragging causing issues

- addons/main/stringtable.xml
Added Polish translation. 100% sure no bugs in it.
> Polish language for stringtable.xml

- addons/main/functions/fnc_addPlayerHoldActions.sqf
- addons/main/initSettings.sqf
- addons/main/stringtable.xml
> Add allow self revive option and action

- addons/main/CfgEden.hpp
- addons/main/XEH_postInit.sqf
- addons/main/functions/fnc_initAIUnit.sqf
- addons/main/stringtable.xml
> Add more 3den properties

- addons/main/XEH_postInit.sqf
- addons/main/functions/fnc_addActionsToUnit.sqf
- addons/main/functions/fnc_addPlayerHoldActions.sqf
- addons/main/functions/fnc_drawDownedUnitIndicator.sqf
- addons/main/functions/fnc_setUnconscious.sqf
> Change icon on downed unit if someone is helping them

- addons/main/XEH_PREP.hpp
- addons/main/XEH_postInit.sqf
- addons/main/functions/fnc_aiMoveAndHealUnit.sqf
- addons/main/functions/fnc_receiveDamage.sqf
- addons/main/functions/fnc_requestAIRevive.sqf
- addons/main/functions/fnc_setUnconscious.sqf
- addons/main/initSettings.sqf
- tools/sqf_linter_LogChecker.py
partially closes #12 
Only ai in players squad can go uncon. Any AI in players squad that has a FAK or has and can use a med kit will be considered to do the revive. Priority is closest unit to downed unit.
Video:
[![IMAGE ALT TEXT](http://img.youtube.com/vi/SK7gkJOKHiw/0.jpg)](http://www.youtube.com/watch?v=SK7gkJOKHiw "Revive demonstration")
> Allow ai unconsciousness and request revive from ai

- addons/main/CfgFactionClasses.hpp
- addons/main/CfgVehicles.hpp
- addons/main/XEH_PREP.hpp
- addons/main/config.cpp
- addons/main/functions/fnc_moduleHeal.sqf
- addons/main/stringtable.xml
> Add zeus heal module

- addons/main/XEH_PREP.hpp
- addons/main/XEH_postInit.sqf
- addons/main/functions/fnc_addActionsToUnit.sqf
- addons/main/functions/fnc_addPlate.sqf
- addons/main/functions/fnc_addPlateKeyPress.sqf
- addons/main/stringtable.xml
> Add ace interaction to add plate

- addons/main/initSettingsACE.sqf
> Scale down plate hp in vest if setting has decreased (ACE mode)

- addons/main/stringtable.xml
Added Polish translations for the latest update's strings.
> Polish strings added

- addons/main/functions/fnc_addPlayerHoldActions.sqf
- addons/main/initSettings.sqf
- addons/main/stringtable.xml
> add confirmation dialog for "Give up" action

- addons/main/stringtable.xml
Simplified and Traditional Chinese added
> Localisation Translation

- addons/main/XEH_PREP.hpp
- addons/main/XEH_postInit.sqf
- addons/main/functions/fnc_fillVestWithPlates.sqf
> Fix adding plates on player respawn

- addons/main/functions/fnc_addActionsToUnit.sqf
> fix medic disconnect issue on reviving units

- addons/main/XEH_PREP.hpp
- addons/main/XEH_postInit.sqf
- addons/main/functions/fnc_canAddPlate.sqf
- addons/main/functions/fnc_hasHealItems.sqf
- addons/main/functions/fnc_uniqueItems.sqf
Fixes #53 
Fixes issue in which it was allowed to add more plates while having none left
> Add support for CDLC or mod firstaid/medkits

- addons/main/functions/fnc_drawDownedUnitIndicator.sqf
- addons/main/initSettings.sqf
- addons/main/stringtable.xml
Adds settings for indicator and timer range, to give medics separate draw ranges.
> Medic range settings

- addons/main/XEH_PREP.hpp
- addons/main/XEH_postInit.sqf
- addons/main/functions/fnc_addActionsToUnit.sqf
- addons/main/functions/fnc_canHold.sqf
- addons/main/functions/fnc_setUnconscious.sqf
- addons/main/initSettings.sqf
- addons/main/stringtable.xml
The thing that made people not die, but doesn't now, except when it should.
Ace interact revive will need the code added to Revive slipped in.
> Add pressure Wound action

- addons/main/XEH_postInit.sqf
CBA doesn't complain about undefined var, apparently, at least in that context.
> Fix Pressure Wound EH undefined var/Ace Interact pfh return

- addons/main/XEH_postInit.sqf
- addons/main/initSettings.sqf
- addons/main/stringtable.xml
> Add hint with remaining FAKs after heal action

- addons/main/XEH_preInit.sqf
- addons/main/functions/fnc_setUnconscious.sqf
- addons/main/initSettings.sqf
- addons/main/stringtable.xml
> Add support for popular radio mods

- addons/main/stringtable.xml
Added missing Polish translations and deleted unnecessary copy of "str_diw_armor_plates_main_bleedouttimercolor"
> Polish translation stringtable.xml

- addons/main/functions/fnc_setUnconscious.sqf
This reverts commit e441a8ed3147752294effb5fa3b21f3d177928f5.
> Revert "Remove `setUnconscious` call when player bleeds out (#90)"

- addons/main/functions/fnc_revive.sqf
> Fix AI driven revive of squad mates

- addons/main/functions/fnc_initPlates.sqf
> Fix error in server log regarding plate ui

- addons/main/stringtable.xml
- Added Korean translation at missing strings
> Translation - Korean

- addons/main/stringtable.xml
> Updated Polish translation

- addons/main/functions/fnc_addActionsToUnit.sqf
- addons/main/functions/fnc_addPlayerHoldActions.sqf
Missed the self-actions when I did the required item setting.
> Fix self-heal/revive with no item required

- addons/compat_ace_fire/stringtable.xml
- addons/compat_ace_overpressure/stringtable.xml
- addons/compat_ace_vehicle_damage/stringtable.xml
- addons/main/stringtable.xml
- Added updated feature strings into Korean
> Translations - Korean

- addons/main/XEH_postInit.sqf
- addons/main/functions/fnc_addPlayerHoldActions.sqf
> Fix ragdolling when force is applied to unit
